version: '3'
services:
    mysql:
        image: mysql:8-debian
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - '3308:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: mysqlroot
        volumes:
            - 'dbdata:/var/lib/mysql'
        networks:
            - phpnetwork
    multiplier:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        ports: 
            - '${APP_PORT:-80}:80'
        networks:
            - phpnetwork
        depends_on:
            - mysql
networks:
    phpnetwork:
        driver: bridge
volumes:
    dbdata:
        driver: local